---
# When triggered it will publish the release only if the changes are related to the
# release
name: new-release

on:
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'
      - 'package.json'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changelog:
              - '**/CHANGELOG.md'
            package:
              - '**/package.json'

      - name: Validate the changes are the ones we need for a release
        if: steps.filter.outputs.changelog != 'true' || steps.filter.outputs.package != 'true'
        run: exit 1

  release:
    runs-on: ubuntu-latest
    needs:
      - validate
    permissions:
      # Needed to write the release changelog
      contents: write
    env:
      ELASTIC_CDN_BUCKET_NAME: apm-rum-357700bc
      ELASTIC_CDN_CREDENTIALS: secret/gce/elastic-cdn/service-account/apm-rum-admin
      SLACK_BUILD_MESSAGE: "Build: (<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>)"
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
    steps:
      - name: Configure github token
        uses: elastic/apm-pipeline-library/.github/actions/github-token@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Read NPM vault secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          method: approle
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            totp/code/npmjs-elasticmachine code | TOTP_CODE

      # This prevent lerna command from throwing this error:
      # "Working tree has uncommitted changes, please commit or remove the following changes before continuing"
      - name: Ignore git uncommitted changes
        run: |
          git update-index --skip-worktree .npmrc

      - name: Configure npm registry
        uses: elastic/apm-pipeline-library/.github/actions/setup-npmrc@current
        with:
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          secret: secret/jenkins-ci/npmjs/elasticmachine
          secret-key: token

      - name: Publish the release
        run: npm run ci:release

      - if: ${{ success() }}
        uses: elastic/apm-pipeline-library/.github/actions/slack-message@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          channel: "#on-week-oblt-productivity"
          message: |
            :runner: [${{ github.repository }}] Release has been published. ${{ env.SLACK_BUILD_MESSAGE }}

      - if: ${{ failure() }}
        uses: elastic/apm-pipeline-library/.github/actions/slack-message@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          channel: "#on-week-oblt-productivity"
          message: |
            :ghost: [${{ github.repository }}] Release failed. ${{ env.SLACK_BUILD_MESSAGE }}
