name: pre-release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: 'Run pre-release process in dry-run mode'
        default: true

permissions:
  contents: read

jobs:
  pre-release:
    runs-on: ubuntu-latest
    permissions:
      # Needed to write the release changelog
      contents: write
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
    steps:
      - name: Configure github token
        uses: elastic/apm-pipeline-library/.github/actions/github-token@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - name: Configure git user
        uses: elastic/apm-pipeline-library/.github/actions/setup-git@current
        with:
          username: ${{ env.GIT_USER }}
          email: ${{ env.GIT_EMAIL }}
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - name: Create Git branch (something unique)
        run: |-
          git checkout -b release-$GITHUB_RUN_ID
          git push origin release-$GITHUB_RUN_ID

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Create PR with the release to be reviewed
        run: npm run ci:pre-release

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: packages/test-2fa-bar

  status:
    if: always()
    needs:
      - pre-release
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: elastic/apm-pipeline-library/.github/actions/check-dependent-jobs@current
        with:
          needs: ${{ toJSON(needs) }}
      - uses: elastic/apm-pipeline-library/.github/actions/notify-build-status@current
        with:
          status: ${{ steps.check.outputs.status }}
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: "#on-week-oblt-productivity"
          message: "Build result for release publication"
