name: release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: 'Run release process in dry-run mode'
        default: true

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # Needed to write the release changelog
      contents: write
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
    steps:
      - name: Configure github token
        uses: elastic/apm-pipeline-library/.github/actions/github-token@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - name: Configure git user
        uses: elastic/apm-pipeline-library/.github/actions/setup-git@current
        with:
          username: ${{ env.GIT_USER }}
          email: ${{ env.GIT_EMAIL }}
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - name: Create Git branch
        run: git checkout -b release

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Create draft release
        env:
          DRY_RUN: ${{ inputs.dry-run }}
        run: npm run ci:release-draft

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: |-
          gh pr create --title "chore(release): publish" --body "As soon as it gets merged the release will be published"

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: packages/test-2fa-bar

  status:
    if: always()
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: elastic/apm-pipeline-library/.github/actions/check-dependent-jobs@current
        with:
          needs: ${{ toJSON(needs) }}
      - uses: elastic/apm-pipeline-library/.github/actions/notify-build-status@current
        if: inputs.dry-run == false
        with:
          status: ${{ steps.check.outputs.status }}
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: "#on-week-oblt-productivity"
          message: "Build result for release publication"
